id: A9D209F8E
base_file: f88AD.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:26:36.594512
  last_modified_at: 2022-06-17 12:26:36.594515
