id: A9D209F8E
base_file: fE83F.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:26:36.610343
  last_modified_at: 2022-06-17 12:26:36.610345
